### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nikuda** [LongSteve/aquastax#5]
I'm about to add a listing of this remake to https://osgameclones.com/ but I don't see any license information? Is it open source or is it meant to be non-permissive license? 

This website might help https://choosealicense.com in choosing an appropriate license. Thanks!

**Comment by LongSteve** [comment]
Thank you for pointing this out @nikuda I had indeed neglected to add a license but have chosen the MIT License. This is an educational project and I want people to benefit from it in any way they like.  Feel free to add links to your web site.
